apiVersion: apps/v1
kind: Deployment
metadata:
  name: documenso-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documenso-app
  template:
    metadata:
      labels:
        app: documenso-app
    spec:
      containers:
        - name: documenso
          image: documenso/documenso:latest
          env:
            - name: NEXT_PUBLIC_WEBAPP_URL
              value: "http://localhost:3000"
            - name: NEXT_PRIVATE_DATABASE_URL
              value: "postgres://documenso:password@documenso-postgres:5432/documenso"
            - name: NEXT_PRIVATE_DIRECT_DATABASE_URL
              value: "postgres://documenso:password@documenso-postgres:5432/documenso"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: documenso-app
spec:
  selector:
    app: documenso-app
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer   # or NodePort if using minikube

